"""
Modèles de données — 19 tables SQLAlchemy.
Import groupé pour faciliter l'utilisation et les migrations Alembic.
"""

from app.core.models.models import (
    ActiviteDOS,
    ActiviteJeunesse,
    ActiviteMusique,
    ActivitePastorale,
    ActiviteProphetique,
    Commentaire,
    Conclusion,
    Coordination,
    DirigeantMusical,
    EncadreurJeunesse,
    Formation,
    InventaireIntendance,
    Mariage,
    MedecineHomme,
    Paroisse,
    PatrimoineImmobilier,
    Rapport,
    ServiteurRH,
    Signataire,
)

__all__ = [
    "ActiviteDOS",
    "ActiviteJeunesse",
    "ActiviteMusique",
    "ActivitePastorale",
    "ActiviteProphetique",
    "Commentaire",
    "Conclusion",
    "Coordination",
    "DirigeantMusical",
    "EncadreurJeunesse",
    "Formation",
    "InventaireIntendance",
    "Mariage",
    "MedecineHomme",
    "Paroisse",
    "PatrimoineImmobilier",
    "Rapport",
    "ServiteurRH",
    "Signataire",
]

from app.core.models.models import (
    ActiviteDOS,
    ActiviteJeunesse,
    ActiviteMusique,
    ActivitePastorale,
    ActiviteProphetique,
    Commentaire,
    Conclusion,
    Coordination,
    DirigeantMusical,
    EncadreurJeunesse,
    Formation,
    InventaireIntendance,
    Mariage,
    MedecineHomme,
    Paroisse,
    PatrimoineImmobilier,
    Rapport,
    ServiteurRH,
    Signataire,
)

__all__ = [
    "Coordination",
    "Rapport",
    "Paroisse",
    "ActivitePastorale",
    "ActiviteProphetique",
    "MedecineHomme",
    "Mariage",
    "Formation",
    "InventaireIntendance",
    "PatrimoineImmobilier",
    "ActiviteDOS",
    "ActiviteMusique",
    "DirigeantMusical",
    "ActiviteJeunesse",
    "EncadreurJeunesse",
    "ServiteurRH",
    "Commentaire",
    "Conclusion",
    "Signataire",
]
